name: Cleanup Old Artifacts

on:
  schedule:
    - cron: '0 0 * * SUN' # Run every Sunday at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Run cleanup script
        run: |
          ARTIFACTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/The-Property-Inspectors-Pty-Ltd/al_generate_pdf_for_report_backend/actions/artifacts \
          | jq -r '.artifacts[] | select(.created_at < "2025-01-01T00:00:00Z") | .id')
          
          for ARTIFACT_ID in $ARTIFACTS; do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/The-Property-Inspectors-Pty-Ltd/al_generate_pdf_for_report_backend/actions/artifacts/$ARTIFACT_ID
          done
